version: 0.2
phases:
  install:
    commands:
      - cd client
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building project...
      - npm run build
  post_build:
    commands:
      - aws s3 sync build s3://keeps-browser --delete
      - echo build completed on `date`
